version: '3.8'

services:
  aegiseye-dashboard:
    build: .
    container_name: aegiseye-dashboard
    ports:
      - "8000:8000"
    restart: always
    environment:
      - N8N_URL=http://n8n_app:5678 # Connects to n8n_app inside Docker network
    networks:
      - infrastructure_internal_net

networks:
  infrastructure_internal_net:
    external: true
    name: infrastructure_internal_net
